### ISSUE TITLE
Readme links to obsidian, the mineral, instead of the software

### ISSUE THREAD

**Issue by caesiumtea** [chrisgrieser/obsidian-theme-design-utilities#4]
Uh hi, ignore this issue if you did this on purpose as a joke, but I noticed that the readme for this repo links to... not the kind of obsidian I was expecting, lol. On line 5, the link around the word Obsidian leads to the Wikipedia article on the actual mineral obsidian. (I poked around and it turns out that there does not actually exist a Wikipedia article for the software anyway.)

https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/a02848094a2b440fe7d03bd7886e1c721e4046da/README.md?plain=1#L5

**Comment by chrisgrieser** [comment]
lol, wasn't a joke, I have no idea how that happened 🤣 

Think I somehow copied the wrong link, and since my markdown editor folds URLs, it seems I have never noticed. Thanks for the tip, just fixed it 🙈

**Comment by caesiumtea** [comment]
Lol, honestly my guess was that you wrote the Readme in Obsidian and had some kind of plugin to automatically turn a word into a Wikipedia link. I mean, I don't know if a plugin like that exists, but given how many plugins are out there it seemed probable enough!

**Comment by chrisgrieser** [comment]
> Lol, honestly my guess was that you wrote the Readme in Obsidian and had some kind of plugin to automatically turn a word into a Wikipedia link

well, not exactly a plugin, but I did use [SearchLink](https://brettterpstra.com/projects/searchlink/) which pretty much does that. Could be that it happened cause of that :P
