### ISSUE TITLE
Feature Request: Add a command to toggle the mobile UI (code snippet in comment)

### ISSUE THREAD

**Issue by YousufSSyed** [chrisgrieser/obsidian-theme-design-utilities#7]
I have my own mobile theme that I may want to work on sometimes, the only way I've found to change Obsidian to the mobile ui on desktop is entering [this snippet](https://marcus.se.net/obsidian-plugin-docs/testing/mobile-devices) in the console:

```
this.app.emulateMobile(!this.app.isMobile);
```

I looked at the [Obsidian Sample Plugin](https://github.com/obsidianmd/obsidian-sample-plugin), and while I'm not very familiar with the Obsidian API, came up with this command to toggle it on and off:

```
    this.addCommand({
      id: "toggle-mobile-view",
      name: "Toggle Mobile View",
      callback: () => {
        this.app.emulateMobile(!this.app.isMobile);
      }
    });
```

**Checklist**
- [x] I have checked that there none of the [other plugins that help with theme development](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/master/README.md#plugins) that does has the requested feature already.

**Comment by chrisgrieser** [comment]
[This is literally the very first command in the README](https://github.com/chrisgrieser/obsidian-theme-design-utilities#mobile-emulation), which the plugin[ implements with the very same code ](implements with the very same code) 😉
